services:
  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgres_container
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      DATABASE_URL: postgresql://admin:admin123@postgres_container/mydatabase
    depends_on:
      - postgres
    networks:
      app_network:

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - C:/Projects/postgres_data:/var/lib/postgresql/data
    networks:
      app_network:

  adminer:
    image: adminer:latest
    container_name: adminer_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      app_network:

networks:
  app_network:
